//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylamaproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcikOturum
    {
        public int ID { get; set; }
        public Nullable<int> OturumID { get; set; }
        public Nullable<int> UyeID { get; set; }
    
        public virtual Oturum Oturum { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
