//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylamaproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oylamasonucu
    {
        public int ID { get; set; }
        public int uyeID { get; set; }
        public int kart { get; set; }
    
        public virtual Uye Uye { get; set; }
    }
}
