//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oylamaproje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oylamaprojedbEntities : DbContext
    {
        public oylamaprojedbEntities()
            : base("name=oylamaprojedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcikOturum> AcikOturum { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Giris> Giris { get; set; }
        public virtual DbSet<Oturum> Oturum { get; set; }
        public virtual DbSet<oylamasonucu> oylamasonucu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
    }
}
